<?xml version="1.0" encoding="UTF-8"?>

<!--
Комплект карт "AnyGIS" для навигатора Guru Maps (https://anygis.herokuapp.com/gurumaps)
Сделан на основе SAS.planet и набора карт от Erelen'a (https://melda.ru/locus/)
Составитель: AnyGIS (anygis@bk.ru)
(02.02.19)

Городские карты
-->

<customMapSource>
<name>OSM Sputnik.ru</name>
<minZoom>0</minZoom>
<maxZoom>19</maxZoom>
<url>http://tiles.maps.sputnik.ru/tiles/kmt2/{$z}/{$x}/{$y}.png'</url>
</customMapSource>
 