<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 02-03-2020 20:51
-->


<customMapSource>
<name>Городские - Google - Ландшафт</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>20</maxZoom>
    <url>http://mt{$serverpart}.google.com/vt/lyrs=t@130,r@206000000&amp;hl=ru&amp;x={$x}&amp;y={$y}&amp;z={$z}&amp;s=Galileo&amp;scale=1&amp;hl=ru</url>
    <serverParts>0 1 2 3</serverParts>
</layer>

</layers>
</customMapSource>