<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 29-02-2020 15:51
-->


<customMapSource>
<name>Туризм - Европа - Северная - Topografisk Norgeskart</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>22</maxZoom>
    <url>https://opencache{$serverpart}.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=topo4&amp;zoom={$z}&amp;x={$x}&amp;y={$y}</url>
    <serverParts>2 3</serverParts>
</layer>

</layers>
</customMapSource>