<?xml version="1.0" encoding="utf-8"?>

<customMapSource>
    <name>⛺ = 🇫🇷 - Ign.fr Topo</name>
    <minZoom>6</minZoom>
    <maxZoom>16</maxZoom>
    <url>https://wxs.ign.fr/essentiels/geoportail/wmts?layer=GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2&amp;style=normal&amp;tilematrixset=PM&amp;Service=WMTS&amp;Request=GetTile&amp;Version=1.0.0&amp;Format=image%2Fpng&amp;TileMatrix={$z}&amp;TileCol={$x}&amp;TileRow={$y}</url>
</customMapSource>
