<?xml version="1.0" encoding="utf-8"?>

<customMapSource overlay="true">
    <name>⏹️ 🏔️ = 🇳🇴 - Ut.no - Лавиноопасность</name>
    <minZoom>0</minZoom>
    <maxZoom>19</maxZoom>
    <url>https://gis3.nve.no/map/rest/services/SkredSnoAktR/MapServer/export?dpi=96&amp;transparent=true&amp;format=png8&amp;layers=show:0,1,2&amp;bbox={bbox}&amp;bboxSR=3857&amp;imageSR=3857&amp;size=512,512&amp;f=image </url>
</customMapSource>