<?xml version="1.0" encoding="utf-8"?>

<customMapSource overlay="true"  overzoom="true">
    <name>⏹️ 📖 = 🇺🇦 - Gov.ua - Кадастровые границы</name>
    <minZoom>0</minZoom>
    <maxZoom>16</maxZoom>
    <url>https://map.land.gov.ua/geowebcache/service/wms?tiled=true&amp;LAYERS=kadastr&amp;STYLES=&amp;FORMAT=image%2Fpng&amp;TRANSPARENT=true&amp;SERVICE=WMS&amp;VERSION=1.1.1&amp;REQUEST=GetMap&amp;SRS=EPSG%3A900913&amp;BBOX={bbox}&amp;WIDTH=256&amp;HEIGHT=256</url>
</customMapSource>