<?xml version="1.0" encoding="utf-8"?>



<customMapSource>
<name>⏹️ 📞 = 🇷🇺 - Мегафон - Все слои (converted)</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>19</maxZoom>
    <url>http://tiles.maps.sputnik.ru/tiles/kmt2/{$z}/{$x}/{$y}.png</url>
</layer>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>12</maxZoom>
    <url>https://anygis.ru/api/v1/Mobile_Coverage_Megafon/{$x}/{$y}/{$z}</url>
</layer>

</layers>
</customMapSource>