<?xml version="1.0" encoding="utf-8"?>

<customMapSource overlay="true"  overzoom="true">
    <name>⏹️ 🚗 = Bing - Пробки</name>
    <minZoom>0</minZoom>
    <maxZoom>19</maxZoom>
    <url>http://t0-traffic.tiles.virtualearth.net/comp/ch/{$quad}?it=Z,TF&amp;n=z&amp;key=AsJ0iq1Xwy4D_2XMs--j7iYkFGQmPTBj0yClUYLncOmDeuyCc0FNhocTT4D2Guqe&amp;tc=9875692</url>
    <serverParts>1 2 3</serverParts>
</customMapSource>