<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 01-03-2020 14:09
-->


<customMapSource>
<name>Спутниковые - Maxar Standard</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>22</maxZoom>
    <url>https://services.digitalglobe.com/earthservice/tmsaccess/tms/1.0.0/DigitalGlobe:ImageryTileService@EPSG:3857@jpg/{$z}/{$x}/{$invY}.jpg?connectId=f57b8754-0d70-4439-bdb4-641beea5c2ec</url>
</layer>

</layers>
</customMapSource>