<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 02-03-2020 20:51
-->


<customMapSource>
<name>Спутниковые - Mapbox</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>17</maxZoom>
    <url>http://api.tiles.mapbox.com/v4/mapbox.satellite/{$z}/{$x}/{$y}.png?access_token=pk.eyJ1IjoienZlcmlrIiwiYSI6IjVLMGxwbGsifQ.pdb83NbjTrfl9ibbdjPSsg</url>
</layer>

</layers>
</customMapSource>