<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 02-03-2020 20:51
-->


<customMapSource>
<name>Спутниковые - Bing Bird's Eye</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>19</maxZoom>
    <url>http://ak.dynamic.t{$serverpart}.tiles.virtualearth.net/comp/ch/{$quad}?mkt=en-us&amp;it=A,G,L&amp;shading=hill&amp;og=8&amp;n=z</url>
    <serverParts>1 2 3</serverParts>
</layer>

</layers>
</customMapSource>