<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 15-10-2019 17:36
-->


<customMapSource>
<name>ERSI World Navigation Charts</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>10</maxZoom>
    <url>https://services.arcgisonline.com/arcgis/rest/services/Specialty/World_Navigation_Charts/MapServer/tile/{$z}/{$y}/{$x}</url>
</layer>

</layers>
</customMapSource>