<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 06-10-2019 22:03
-->


<customMapSource>
<name>Great Britain Topo</name>
<layers>

<layer>
    <minZoom>11</minZoom>
    <maxZoom>15</maxZoom>
    <url>https://ecn.t{$serverpart}.tiles.virtualearth.net/tiles/r{$quad}?g=6948&amp;lbl=l1&amp;productSet=mmOS&amp;key=AmHj4RMhOs0a4O3uk3m144GJik4Y-SIuy1bheg8rGeLFQA3N-Gqs0fJPLRFnuJSd</url>
    <serverParts>1 2 3</serverParts>
</layer>

</layers>
</customMapSource>