<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 17-10-2019 23:24
-->


<customMapSource>
<name>Topografisk Norgeskart 4 - Гибрид</name>
<layers>

<layer>
    <minZoom>5</minZoom>
    <maxZoom>21</maxZoom>
    <url>http://maptiles{$serverpart}.finncdn.no/tileService/1.0.3/norhybrid/{$z}/{$x}/{$y}.png</url>
    <serverParts>1 2 3 4</serverParts>
</layer>

</layers>
</customMapSource>