<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 17-10-2019 23:24
-->


<customMapSource>
<name>TomTom (ночь)</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>18</maxZoom>
    <url>https://{$serverpart}-mydrive.api-system.tomtom.com/map/1/tile/basic/night/{$z}/{$x}/{$y}.png?key=sATA9OwG11zrMKQcCxR3eSEjj2n8Jsrg</url>
    <serverParts>a b c d</serverParts>
</layer>

</layers>
</customMapSource>