<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 06-10-2019 22:36
-->


<customMapSource>
<name>Google Спутник (гибрид) RU</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>20</maxZoom>
    <url>http://mt{$serverpart}.google.com/vt/lyrs=y@176103410&amp;x={$x}&amp;y={$y}&amp;z={$z}&amp;s=Galileoscale=1&amp;hl=ru</url>
    <serverParts>0 1 2 3</serverParts>
</layer>

</layers>
</customMapSource>