<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 12-10-2019 00:48
-->


<customMapSource>
<name>Thunderforest Transport Dark</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>22</maxZoom>
    <url>http://{$serverpart}.tile.thunderforest.com/transport-dark/{$z}/{$x}/{$y}.png?apikey=6170aad10dfd42a38d4d8c709a536f38</url>
    <serverParts>a b c</serverParts>
</layer>

</layers>
</customMapSource>