<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 12-10-2019 00:48
-->


<customMapSource>
<name>Google Bike RU</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>20</maxZoom>
    <url>http://mt{$serverpart}.google.com/vt/lyrs=m@486000000,bike&amp;src=app&amp;x={$x}&amp;y={$y}&amp;z={$z}&amp;s=Gali&amp;hl=ru&amp;scale=1</url>
    <serverParts>0 1 2 3</serverParts>
</layer>

</layers>
</customMapSource>