<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 17-10-2019 23:09
-->


<customMapSource>
<name>Mapbox Terrain</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>18</maxZoom>
    <url>http://{$serverpart}.tiles.mapbox.com/v4/matt.72ef5189/{$z}/{$x}/{$y}.png?access_token=pk.eyJ1IjoiZHVuY2FuZ3JhaGFtIiwiYSI6IlJJcWdFczQifQ.9HUpTV1es8IjaGAf_s64VQ</url>
    <serverParts>a b c</serverParts>
</layer>

</layers>
</customMapSource>