<?xml version="1.0" encoding="UTF-8"?>

<!--
Комплект карт "AnyGIS" для навигатора Guru Maps (https://anygis.herokuapp.com/gurumaps)
Сделан на основе SAS.planet и набора карт от Erelen'a (https://melda.ru/locus/)
Составитель: AnyGIS (anygis@bk.ru)
(02.02.19)

Растровые топографические карты
-->

<customMapSource>
<name>Nakarte.me: Топокарта 10км (Евразия частично)</name>
<minZoom>0</minZoom>
<maxZoom>9</maxZoom>
<url>https://tiles.nakarte.me/topo001m/{$z}/{$x}/{$invY}</url>
</customMapSource>
