<?xml version="1.0" encoding="UTF-8"?>

<!--
Комплект карт "AnyGIS" для навигатора Guru Maps (https://anygis.herokuapp.com/gurumaps)
Сделан на основе SAS.planet и набора карт от Erelen'a (https://melda.ru/locus/)
Составитель: AnyGIS (anygis@bk.ru)
(02.02.19)

Растровые топографические карты
-->

<customMapSource>
<name>SasPlanet: Генштаб 5 км</name>
<minZoom>0</minZoom>
<maxZoom>11</maxZoom>
<url>https://anygis.herokuapp.com/Locals_Genshtab_05000/{$x}/{$y}/{$z}</url>
</customMapSource>
