<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
<name>Eniro Hybrid</name>
<layers>
<layer>
<url>http://{$serverpart}.eniro.no/geowebcache/service/tms1.0.0/aerial/{$z}/{$x}/{$invY}.jpeg</url>
<serverParts>map01 map02 map03 map04</serverParts>
</layer>
<layer>
<url>http://{$serverpart}.eniro.no/geowebcache/service/tms1.0.0/hybrid2x/{$z}/{$x}/{$invY}.png</url>
<serverParts>map01 map02 map03 map04</serverParts>
</layer>
</layers>
</customMapSource>
