<?xml version="1.0" encoding="UTF-8"?>

<!--
Комплект карт "AnyGIS" для навигатора Guru Maps (https://anygis.herokuapp.com/gurumaps)
Сделан на основе SAS.planet и набора карт от Erelen'a (https://melda.ru/locus/)
Составитель: AnyGIS (anygis@bk.ru)
(02.02.19)

Карты на основе OpenStreetMaps
-->

<customMapSource>
<name>4Umaps.eu</name>
<minZoom>0</minZoom>
<maxZoom>16</maxZoom>
<url>http://www.4umaps.eu/{$z}/{$x}/{$y}.png</url>
</customMapSource>