<?xml version="1.0" encoding="utf-8"?>

<customMapSource>
    <name>🏠 = Here</name>
    <minZoom>0</minZoom>
    <maxZoom>19</maxZoom>
    <url>https://{$serverpart}.base.maps.api.here.com/maptile/2.1/maptile/newest/normal.day/{$z}/{$x}/{$y}/256/png8?app_id=xWVIueSv6JL0aJ5xqTxb&amp;app_code=djPZyynKsbTjIUDOBcHZ2g&amp;lg=eng&amp;ppi=72</url>
    <serverParts>1 2 3 4</serverParts>
</customMapSource>