<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 29-02-2020 13:20
-->


<customMapSource>
<name>City - Europe - Northern - Eniro</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>22</maxZoom>
    <url>http://map0{$serverpart}.eniro.no/geowebcache/service/tms1.0.0/map/{$z}/{$x}/{$invY}.png</url>
    <serverParts>1 2 3 4</serverParts>
</layer>

</layers>
</customMapSource>