<?xml version="1.0" encoding="utf-8"?>

<customMapSource>
    <name>⛺ = 🇫🇷 - Ign.fr Topo</name>
    <minZoom>6</minZoom>
    <maxZoom>16</maxZoom>
    <url>https://wxs.ign.fr/an7nvfzojv5wa96dsga5nk8w/geoportail/wmts?layer=GEOGRAPHICALGRIDSYSTEMS.MAPS.SCAN25TOUR.CV&amp;style=normal&amp;tilematrixset=PM&amp;Service=WMTS&amp;Request=GetTile&amp;Version=1.0.0&amp;Format=image%2Fjpeg&amp;TileMatrix={$z}&amp;TileCol={$x}&amp;TileRow={$y}</url>
</customMapSource>