<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 29-02-2020 21:15
-->


<customMapSource>
<name>Hike - Europe - Northern - Norway UT.no - Topolart</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>19</maxZoom>
    <url>https://opencache.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=topo4&amp;zoom={$z}&amp;x={$x}&amp;y={$y}</url>
</layer>

</layers>
</customMapSource>