<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 01-03-2020 14:09
-->


<customMapSource>
<name>Hike - Europe - Northern - Norway UT.no - Papirkart</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>19</maxZoom>
    <url>https://opencache.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=toporaster3&amp;zoom={$z}&amp;x={$x}&amp;y={$y}</url>
</layer>

</layers>
</customMapSource>