<?xml version="1.0" encoding="utf-8"?>

<customMapSource>
    <name>⛺ = 🇸🇪 - Lantmäteriets Topografisk</name>
    <minZoom>0</minZoom>
    <maxZoom>22</maxZoom>
    <url>https://kso.etjanster.lantmateriet.se/karta/topowebb/v1.1/wmts?SERVICE=WMTS&amp;REQUEST=GetTile&amp;VERSION=1.0.0&amp;LAYER=topowebb&amp;STYLE=default&amp;TILEMATRIXSET=3857&amp;TILEMATRIX={$z}&amp;TILEROW={$y}&amp;TILECOL={$x}&amp;FORMAT=image/png</url>
</customMapSource>