<?xml version="1.0" encoding="utf-8"?>

<customMapSource overlay="true"  overzoom="true">
    <name>⏹️ ⚓️ = OSM OpenSeaMap - Deep Map</name>
    <minZoom>0</minZoom>
    <maxZoom>19</maxZoom>
    <url>http://osm.franken.de:8080/geoserver/gwc/service/wmts?layer=gebco_2014&amp;style=&amp;tilematrixset=EPSG%3A900913&amp;Service=WMTS&amp;Request=GetTile&amp;Version=1.0.0&amp;Format=image%2Fpng&amp;TileMatrix=EPSG%3A900913%3A{$z}&amp;TileCol={$x}&amp;TileRow={$y}</url>
</customMapSource>