<?xml version="1.0" encoding="utf-8"?>

<customMapSource overlay="true">
    <name>⏹️ 🚗 = Here - Flow</name>
    <minZoom>0</minZoom>
    <maxZoom>19</maxZoom>
    <url>https://{$serverpart}.traffic.maps.cit.api.here.com/maptile/2.1/flowtile/newest/normal.day/{$z}/{$x}/{$y}/256/png8?app_id=bC4fb9WQfCCZfkxspD4z&amp;app_code=K2Cpd_EKDzrZb1tz0zdpeQ&amp;lg=rus&amp;ppi=72&amp;pview=RUS&amp;tprof=PrtlHere</url>
    <serverParts>1 2 3 4</serverParts>
</customMapSource>