<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 02-03-2020 20:51
-->


<customMapSource>
<name>Satellites - Europe - Northern - Topografisk Norgeskart </name>
<layers>

<layer>
    <minZoom>5</minZoom>
    <maxZoom>21</maxZoom>
    <url>http://maptiles{$serverpart}.finncdn.no/tileService/1.0.3/norortho/{$z}/{$x}/{$y}.png</url>
    <serverParts>1 2 3 4</serverParts>
</layer>

</layers>
</customMapSource>