<?xml version="1.0" encoding="utf-8"?>

<customMapSource>
    <name>🛰 = 🇷🇺 - Kosmosnimki.ru</name>
    <minZoom>0</minZoom>
    <maxZoom>17</maxZoom>
    <url>https://maps.kosmosnimki.ru/TileSender.ashx?ModeKey=tile&amp;ftc=osm&amp;z={$z}&amp;x={$x}&amp;y={$y}&amp;srs=3857&amp;sw=1&amp;LayerName=C9458F2DCB754CEEACC54216C7D1EB0A&amp;key=N%2BAz7iqqkgEre1TcrZ09kjGG7KYIRZb8VI6E3K5EhXugkv3rRQMm2Zc74w7S1ILt0QU8kCiQdHlUr%2BRksXWYs3QZhT%2B1yvc35G58bgSaKRQ%3D</url>
    <serverParts>a b c d</serverParts>
</customMapSource>