<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 01-03-2020 20:55
-->


<customMapSource>
<name>Satellites - America - USGS National Map - Satellite Plus</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>13</maxZoom>
    <url>http://basemap.nationalmap.gov/ArcGIS/rest/services/USGSImageryTopo/MapServer/tile/{$z}/{$y}/{$x}</url>
</layer>

</layers>
</customMapSource>