<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 05-01-2020 16:27
-->


<customMapSource>
<name>Hitta Frilufts + Skoterleder</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>22</maxZoom>
    <url>https://tiles.skoterleder.org/tiles/{$z}/{$x}/{$y}.png</url>
</layer>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>22</maxZoom>
    <url>https://overl.skoterleder.org/tiles/{$z}/{$x}/{$y}.png</url>
</layer>

</layers>
</customMapSource>