<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 17-10-2019 23:15
-->


<customMapSource>
<name>Maxar Standard - Satellite</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>22</maxZoom>
    <url>https://earthwatch.digitalglobe.com/earthservice/tmsaccess/tms/1.0.0/DigitalGlobe:ImageryTileService@EPSG:3857@jpg/{$z}/{$x}/{$invY}.jpg?connectId=d9c5e3ef-6300-4cec-9562-c1f27da6b2d9 </url>
</layer>

</layers>
</customMapSource>