<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 16-10-2019 15:47
-->


<customMapSource>
<name>Google Map</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>20</maxZoom>
    <url>https://mt{$serverpart}.google.com/vt/lyrs=m&amp;hl=en&amp;x={$x}&amp;y={$y}&amp;z={$z}&amp;scale=1</url>
    <serverParts>0 1 2 3</serverParts>
</layer>

</layers>
</customMapSource>