<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 06-10-2019 22:03
-->


<customMapSource>
<name>Mapbox Satellite</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>17</maxZoom>
    <url>http://api.tiles.mapbox.com/v4/mapbox.satellite/{$z}/{$x}/{$y}.png?access_token=pk.eyJ1IjoienZlcmlrIiwiYSI6IjVLMGxwbGsifQ.pdb83NbjTrfl9ibbdjPSsg</url>
    <serverParts>a b c</serverParts>
</layer>

</layers>
</customMapSource>