<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 18-01-2020 18:58
-->


<customMapSource>
<name>Google - Satellite</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>20</maxZoom>
    <url>http://mt{$serverpart}.google.com/vt/lyrs=s@176103410&amp;x={$x}&amp;y={$y}&amp;z={$z}&amp;s=Galileo&amp;hl=en</url>
    <serverParts>0 1 2 3</serverParts>
</layer>

</layers>
</customMapSource>