<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 24-10-2019 23:33
-->


<customMapSource>
<name>Maxar Premium - Satellite</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>22</maxZoom>
    <url>https://earthwatch.digitalglobe.com/earthservice/tmsaccess/tms/1.0.0/DigitalGlobe:ImageryTileService@EPSG:3857@jpg/{$z}/{$x}/{$invY}.jpg?connectId=91e57457-aa2d-41ad-a42b-3b63a123f54a</url>
</layer>

</layers>
</customMapSource>