<?xml version="1.0" encoding="UTF-8"?>

<!--
Комплект карт "AnyGIS" для навигатора Guru Maps (https://anygis.herokuapp.com/gurumaps)
Сделан на основе SAS.planet и набора карт от Erelen'a (https://melda.ru/locus/)
Составитель: AnyGIS (anygis@bk.ru)
(02.02.19)

Карты восточной Европы
-->

<customMapSource>
<name>Meta.ua</name>
<minZoom>0</minZoom>
<maxZoom>19</maxZoom>
<url>http://i1.map.meta.ua/cell.php?x={$x}&amp;y={$y}&amp;scale={$z}.x</url>
</customMapSource>
 