<?xml version="1.0" encoding="UTF-8"?>

<!--
Комплект карт "AnyGIS" для навигатора Guru Maps (https://anygis.herokuapp.com/gurumaps)
Сделан на основе набора карт от ms.Galileo-app (https://ms.galileo-app.com/)
Составитель: AnyGIS (anygis@bk.ru)
(02.02.19)

Растровые топографические карты
-->

<customMapSource>
<name>Топокарта Маршруты.РУ</name>
<minZoom>0</minZoom>
<maxZoom>15</maxZoom>
<url>http://maps.marshruty.ru/ml.ashx?al=1&amp;x={$x}&amp;y={$y}&amp;z={$z}&amp;i=1</url>
</customMapSource>
