<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
	<name>Here.com Terrain</name>
	<minZoom>0</minZoom>
	<maxZoom>19</maxZoom>
	<url>https://{$serverpart}.aerial.maps.api.here.com/maptile/2.1/maptile/newest/terrain.day/{$z}/{$x}/{$y}/512/png8?app_id=xWVIueSv6JL0aJ5xqTxb&amp;app_code=djPZyynKsbTjIUDOBcHZ2g&amp;lg=rus&amp;ppi=72&amp;pview=DEF</url>
	<serverParts>1 2 3 4</serverParts>
</customMapSource>
