<?xml version="1.0" encoding="utf-8"?>

<customMapSource overlay="true"  overzoom="true">
    <name>⏹️ 🏷 = OSM Mapbox - Гибрид</name>
    <minZoom>0</minZoom>
    <maxZoom>22</maxZoom>
    <url>http://{$serverpart}.tiles.mapbox.com/v4/openstreetmap.map-inh76ba2/{$z}/{$x}/{$y}.png?access_token=pk.eyJ1Ijoib3BlbnN0cmVldG1hcCIsImEiOiJjaml5MjVyb3MwMWV0M3hxYmUzdGdwbzE4In0.q548FjhsSJzvXsGlPsFxAQ</url>
    <serverParts>a b c d</serverParts>
</customMapSource>