<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 08-09-2019 21:41
-->


<customMapSource>
<name>2Gis</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>18</maxZoom>
    <url>https://tile{$serverpart}.maps.2gis.com/tiles?x={$x}&amp;y={$y}&amp;z={$z}&amp;v=1.5&amp;r=g&amp;ts=online_sd</url>
    <serverParts>0 1 2 3</serverParts>
</layer>

</layers>
</customMapSource>