<?xml version="1.0" encoding="UTF-8"?>

<!--
Комплект карт "AnyGIS" для навигатора Guru Maps (https://anygis.herokuapp.com/gurumaps)
Сделан на основе SAS.planet и набора карт от Erelen'a (https://melda.ru/locus/)
Составитель: AnyGIS (anygis@bk.ru)
(02.02.19)

Спутниковые карты
-->

<customMapSource>
	<name>Mapbox.com Satellite</name>
	<minZoom>0</minZoom>
	<maxZoom>19</maxZoom>
	<url>https://a.tiles.mapbox.com/v3/tmcw.map-j5fsp01s/{$z}/{$x}/{$y}.png</url>
</customMapSource>
