<?xml version="1.0" encoding="UTF-8"?>

<!--
Комплект карт "AnyGIS" для навигатора Guru Maps (https://anygis.herokuapp.com/gurumaps)
Сделан на основе SAS.planet и набора карт от Erelen'a (https://melda.ru/locus/)
Составитель: AnyGIS (anygis@bk.ru)
(02.02.19)

Растровые топографические карты
-->

<customMapSource>
<name>Nakarte.me: ГГЦ 250м (Россия частично)</name>
<minZoom>0</minZoom>
<maxZoom>15</maxZoom>
<url>https://tiles.nakarte.me/ggc250/{$z}/{$x}/{$invY}</url>
</customMapSource>
