<?xml version="1.0" encoding="utf-8"?>

<!--
Map pack from AnyGIS.ru
Updated: 07-01-2020 12:41
-->


<customMapSource>
<name>Bing</name>
<layers>

<layer>
    <minZoom>0</minZoom>
    <maxZoom>19</maxZoom>
    <url>http://ecn.dynamic.t{$serverpart}.tiles.virtualearth.net/comp/ch/{$quad}?mkt=en-us&amp;it=G,VE,BX,L,LA&amp;shading=hill&amp;og=2&amp;n=z</url>
    <serverParts>1 2 3</serverParts>
</layer>

</layers>
</customMapSource>