<?xml version="1.0" encoding="UTF-8"?>

<!--
Комплект карт "AnyGIS" для навигатора Guru Maps (https://anygis.herokuapp.com/gurumaps)
Сделан на основе SAS.planet и набора карт от Erelen'a (https://melda.ru/locus/)
Составитель: AnyGIS (anygis@bk.ru)
(02.02.19)

Спутниковые карты
-->
 
<customMapSource>
<name>Wikimapia.org + Google Satellite </name>
<minZoom>0</minZoom>
<maxZoom>21</maxZoom>
<url>https://anygis.herokuapp.com/Wikimapia_sat_google/{$x}/{$y}/{$z}</url>
</customMapSource>


 