<?xml version="1.0" encoding="UTF-8"?>

<!--
Комплект карт "AnyGIS" для навигатора Guru Maps (https://anygis.herokuapp.com/gurumaps)
Сделан на основе набора карт от ms.Galileo-app (https://ms.galileo-app.com/)
Составитель: AnyGIS (anygis@bk.ru)
(02.02.19)

Новая Зеландия
-->

<customMapSource>
    <name>NZ Topo</name>
    <minZoom>6</minZoom>
    <maxZoom>15</maxZoom>
    <url>http://nz1.nztopomaps.com/{$z}/{$x}/{$invY}.png</url>
</customMapSource>
