<?xml version="1.0" encoding="UTF-8"?>

<!--
Комплект карт "AnyGIS" для навигатора Guru Maps (https://anygis.herokuapp.com/gurumaps)
Сделан на основе SAS.planet и набора карт от Erelen'a (https://melda.ru/locus/)
Составитель: AnyGIS (anygis@bk.ru)
(02.02.19)

Карты центральной Азии
-->

<customMapSource>
<name>SasPlanet: Тянь-Шань и Памир</name>
<minZoom>0</minZoom>
<maxZoom>15</maxZoom>
<url>https://anygis.herokuapp.com/Local_Tyan_shan1/{$x}/{$y}/{$z}</url>
</customMapSource>


 