<?xml version="1.0" encoding="UTF-8"?>
<!--

AnyGIS for Galileo converter, (01.11.2018)

Преобразователь URL-запров на карты с простой нумерацией (как в OSM) 
в форматы картографисеских сервисов со сложной нумерацией тайлов.
Автор: Max K (nnngrach@gmail.com)

-->
<customMapSource>
<name>Yandex: Map</name>
<minZoom>0</minZoom>
<maxZoom>19</maxZoom>
<url>http://nnngrach.h1n.ru/AnyGIS.php?mode=convertFromWGS84&amp;mapName=Yandex_map&amp;x={$x}&amp;y={$y}&amp;z={$z}</url>
</customMapSource>


 