<?xml version="1.0" encoding="UTF-8"?>

<!--
Комплект карт "AnyGIS" для навигатора Guru Maps (https://anygis.herokuapp.com/gurumaps)
Сделан на основе Сustom-map-source (https://custom-map-source.appspot.com/)
Составитель: AnyGIS (anygis@bk.ru)
(02.02.19)

Карты северной Европы
-->

<customMapSource>
<name>Lantmäteriets Fjällkarta</name>
<minZoom>5</minZoom>
<maxZoom>12</maxZoom>
<url>https://johanberonius.github.io/Lantmateriets-Fjallkarta/tiles/{$z}/{$x}/{$y}.jpg</url>
</customMapSource>
