<?xml version="1.0" encoding="UTF-8"?>

<!--
Комплект карт "AnyGIS" для навигатора Guru Maps (https://anygis.herokuapp.com/gurumaps)
Сделан на основе Сustom-map-source (https://custom-map-source.appspot.com/)
Составитель: AnyGIS (anygis@bk.ru)
(02.02.19)

Карты северной Европы
-->

<customMapSource>
<name>FINN Kart Norge</name>
<url>http://maptiles{$serverpart}.finncdn.no/tileService/1.0.3/normaphd/{$z}/{$x}/{$y}.png</url>
<serverParts>1 2 3 4</serverParts>
</customMapSource>